export const mockChildrenData = [
  {
    childId: '1',
    name: {
      fullName: 'John Doe',
      firstName: 'John',
      middleName: '',
      lastName: 'Doe',
    },
    checkedIn: true,
    pickupTime: '16:00',
    institutionId: 'institution1',
    groupId: 'group1',
    createdTime: '2021-09-01T08:30:00Z',
    birthday: null,
    homeAddress: null,
    extraInfo: '',
    language: 'English',
    nationality: 'American',
    birthplace: 'USA',
    gender: 1,
    startDate: '2021-09-01',
    endDate: null,
    leavingReason: null,
    isTestChild: false,
    relations: [],
    image: { small: '', large: '', empty: true, colorCode: 0 },
    isSleeping: false,
    naps: [],
    hasVacation: false,
    isSick: false,
    isAbsent: false,
    leaves: [],
    onBus: false,
    onTrip: false,
    statuses: [],
    statusRegistrations: [],
    checkins: [],
    checkinTime: '2021-09-01T08:30:00Z',
    pickupRelationId: null,
    pickupName: 'Parent 1',
  },
  {
    childId: '2',
    name: {
      fullName: 'Jane Smith',
      firstName: 'Jane',
      middleName: '',
      lastName: 'Smith',
    },
    checkedIn: false,
    pickupTime: '17:00',
    institutionId: 'institution2',
    groupId: 'group2',
    createdTime: '2021-09-01T08:30:00Z',
    birthday: null,
    homeAddress: null,
    extraInfo: '',
    language: 'English',
    nationality: 'British',
    birthplace: 'UK',
    gender: 2,
    startDate: '2021-09-01',
    endDate: null,
    leavingReason: null,
    isTestChild: false,
    relations: [],
    image: { small: '', large: '', empty: true, colorCode: 0 },
    isSleeping: false,
    naps: [],
    hasVacation: false,
    isSick: false,
    isAbsent: false,
    leaves: [],
    onBus: false,
    onTrip: false,
    statuses: [],
    statusRegistrations: [],
    checkins: [],
    checkinTime: null,
    pickupRelationId: null,
    pickupName: '',
  },
]
